"""add paper trading

Revision ID: efaa6bb1a665
Revises: 5ce7bf593b5b
Create Date: 2026-08-23 12:37:54.897434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efaa6bb1a665'
down_revision: Union[str, Sequence[str], None] = '5ce7bf593b5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper_trades',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('total_value', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_trades_executed_at'), 'paper_trades', ['executed_at'], unique=False)
    op.create_index(op.f('ix_paper_trades_symbol'), 'paper_trades', ['symbol'], unique=False)
    op.create_index(op.f('ix_paper_trades_user_id'), 'paper_trades', ['user_id'], unique=False)
    op.create_table('paper_trading_accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('initial_capital', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('available_cash', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_trading_accounts_user_id'), 'paper_trading_accounts', ['user_id'], unique=True)
    op.create_table('paper_trading_positions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('average_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'symbol', name='uq_paper_position_user_symbol')
    )
    op.create_index(op.f('ix_paper_trading_positions_symbol'), 'paper_trading_positions', ['symbol'], unique=False)
    op.create_index(op.f('ix_paper_trading_positions_user_id'), 'paper_trading_positions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paper_trading_positions_user_id'), table_name='paper_trading_positions')
    op.drop_index(op.f('ix_paper_trading_positions_symbol'), table_name='paper_trading_positions')
    op.drop_table('paper_trading_positions')
    op.drop_index(op.f('ix_paper_trading_accounts_user_id'), table_name='paper_trading_accounts')
    op.drop_table('paper_trading_accounts')
    op.drop_index(op.f('ix_paper_trades_user_id'), table_name='paper_trades')
    op.drop_index(op.f('ix_paper_trades_symbol'), table_name='paper_trades')
    op.drop_index(op.f('ix_paper_trades_executed_at'), table_name='paper_trades')
    op.drop_table('paper_trades')
    # ### end Alembic commands ###
